//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_gaming.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lab-gaming.Resx.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW WORD.
        /// </summary>
        internal static string ButtonNewWord {
            get {
                return ResourceManager.GetString("ButtonNewWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETRY RANDOM.
        /// </summary>
        internal static string ButtonRetryRandom {
            get {
                return ResourceManager.GetString("ButtonRetryRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIES WASTED.
        /// </summary>
        internal static string Defeat {
            get {
                return ResourceManager.GetString("Defeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERASE.
        /// </summary>
        internal static string Erase {
            get {
                return ResourceManager.GetString("Erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERASE].
        /// </summary>
        internal static string EraseDB {
            get {
                return ResourceManager.GetString("EraseDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME.
        /// </summary>
        internal static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HISTORY.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFAULT.
        /// </summary>
        internal static string MakeDefault {
            get {
                return ResourceManager.GetString("MakeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICTIONARY STRICT.
        /// </summary>
        internal static string MakeStrict {
            get {
                return ResourceManager.GetString("MakeStrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYER NAME.
        /// </summary>
        internal static string PlayerNamePlace {
            get {
                return ResourceManager.GetString("PlayerNamePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMIZE.
        /// </summary>
        internal static string PlayerSwitch {
            get {
                return ResourceManager.GetString("PlayerSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIVE LETTERS, SIX TRIES..
        /// </summary>
        internal static string RulesFirstLine {
            get {
                return ResourceManager.GetString("RulesFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLORS ARE THE HINTS..
        /// </summary>
        internal static string RulesSecondLine {
            get {
                return ResourceManager.GetString("RulesSecondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SERVER OFFLINE].
        /// </summary>
        internal static string ServerOfflineIndicator {
            get {
                return ResourceManager.GetString("ServerOfflineIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SERVER ONLINE].
        /// </summary>
        internal static string ServerOnlineIndicator {
            get {
                return ResourceManager.GetString("ServerOnlineIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEFAULT].
        /// </summary>
        internal static string SetAsDefault {
            get {
                return ResourceManager.GetString("SetAsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STRICT.
        /// </summary>
        internal static string StrictIndicator {
            get {
                return ResourceManager.GetString("StrictIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NOT STARTED].
        /// </summary>
        internal static string TimerNotStarted {
            get {
                return ResourceManager.GetString("TimerNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIES.
        /// </summary>
        internal static string TriesCount {
            get {
                return ResourceManager.GetString("TriesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREE.
        /// </summary>
        internal static string UnStrictIndicator {
            get {
                return ResourceManager.GetString("UnStrictIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOLVED.
        /// </summary>
        internal static string Victory {
            get {
                return ResourceManager.GetString("Victory", resourceCulture);
            }
        }
    }
}
